// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudE7F7tNZMM9mA6Bk2BaXgFsflgHu9VY',
    appId: '1:369448418901:web:c0b000ff44e76062d31edc',
    messagingSenderId: '369448418901',
    projectId: 'smart-shopper-5193d',
    authDomain: 'smart-shopper-5193d.firebaseapp.com',
    storageBucket: 'smart-shopper-5193d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TrhnqGrauwwZ-34ujo0GSyOEBu87OgE',
    appId: '1:369448418901:android:4df6e4df62c73a5ad31edc',
    messagingSenderId: '369448418901',
    projectId: 'smart-shopper-5193d',
    storageBucket: 'smart-shopper-5193d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudE7F7tNZMM9mA6Bk2BaXgFsflgHu9VY',
    appId: '1:369448418901:web:6a9d8c36bf440bcdd31edc',
    messagingSenderId: '369448418901',
    projectId: 'smart-shopper-5193d',
    authDomain: 'smart-shopper-5193d.firebaseapp.com',
    storageBucket: 'smart-shopper-5193d.firebasestorage.app',
  );
}
